### PR TITLE
Update all deps, cleanup scripts

### PR DESCRIPTION
**Pull request by AviVahl**
Upgraded to babel 6, react 15, and all other deps.
Tests pass on Windows as well now.

### CODE REVIEW

**Comment by AviVahl** [comment]
I'm not sure what is up with this CI. Appears to reset connection on `npm install`... :/
Anyhow, tests all pass on my end. Please check it on your end.

**Comment by hexpunk** [comment]
Any movement on this?  chai-react-element depends on this library and we'd like to update to the latest version of react.

**Comment by hexpunk** [comment]
The CI build continues to fail with the error `npm ERR! Callback called more than once.`  I think the `ECONNRESET` errors are a red herring because npm seems to recover from them.

May be related to https://github.com/npm/npm/issues/12580 and/or https://github.com/npm/npm/issues/4169?

**Comment by AviVahl** [comment]
Does everything look fine on your end though? (local machine)

**Comment by AviVahl** [comment]
Project appears to be un-maintained, so closing.

**Comment by rogeriochaves** [comment]
Sorry, for some reason I am not getting notifications for this, even though I'm subscribed. Anyway, yeah, this is unmantained because I don't have a usecase for it anymore, do you have one?

Also, 2 years passed by, there are probably a lot of other alternatives right now :P

**Comment by rogeriochaves** [comment]
Oh, sorry, do you still use it for `chai-react-element`? I'd be glad to accept the PR or even move this repo so you guys can maintain it

**Pull request closed without merging**
